import type { Metadata } from "next";
import {  New_Rocker } from "next/font/google";
import PrelineScriptWrapper from "@/components/PrelineScriptsWrapper";
import "./globals.css";

const newRocker = New_Rocker({
  variable: "--font-new-rocker",
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${newRocker.variable} antialiased`}
      >
        <PrelineScriptWrapper />
        {children}
      </body>
    </html>
  );
}
